
services:
  proxy:
    build: 
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - users
      - budgets
    ports:
      - 8080:80
    volumes:
      - ./proxy:/etc/nginx/
    networks:
      - msaada_network
    
  users:
    build:
      dockerfile: Dockerfile
      context: ./users
    ports:
      - '3001:3001'
    env_file: ./users/.env
    volumes:
      - ./users:/app/
    networks:
      - msaada_network

  budgets:
    build:
      dockerfile: Dockerfile
      context: ./budget
    ports:
      - '3002:3002'
    env_file: ./budget/.env
    volumes:
      - ./budget:/app/
    networks:
      - msaada_network


networks:
  msaada_network:
    name: msaada_network
    external: true

