
services:
  # rabbitmq:
  #   image: rabbitmq:3.13-management
  #   container_name: rabbitmq
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
    # networks:
    #   - msaada_network
      
  user-srv:
    build:
      dockerfile: Dockerfile
      context: ./users
    depends_on:
      - users-db
    ports:
      - 3001:3001
    env_file: ./users/.env
    volumes:
      - ./users:/app/
    # networks:
    #   - msaada_network

  users-db:
    image: postgres:12 
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgresql-user:/var/lib/postgresql
      - postgresql_data-user:/var/lib/postgresql/data

  budget-srv:
    build:
      dockerfile: Dockerfile
      context: ./budget
    depends_on:
      - budget-db
    ports:
      - 3002:3002
    env_file: ./budget/.env
    volumes:
      - ./budget:/app/
    # networks:
    #   - msaada_network

  budget-db:
    image: postgres:12 
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgresql-budget:/var/lib/postgresql
      - postgresql_data-budget:/var/lib/postgresql/data

  proxy:
    build: 
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - user-srv
      - budget-srv
    ports:
      - 8080:80
    volumes:
      - ./proxy:/etc/nginx/
    # networks:
    #   - msaada_network

# networks:
#   msaada_network:
#     name: msaada_network

volumes:
  postgresql_data-user:
  postgresql-user:
  postgresql_data-budget:
  postgresql-budget:
