
services:
  proxy:
    build: 
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - users
      - transactions
    ports:
      - 80:80
    
  users:
    build:
      dockerfile: Dockerfile
      context: ./users
    ports:
      - '3001:3001'
    env_file: ./users/.env
    volumes:
      - ./users:/app/users

  transactions:
    build:
      dockerfile: Dockerfile
      context: ./transaction
    ports:
      - '3001:3001'
    env_file: ./transaction/.env
    volumes:
      - ./transaction:/app/transaction