
services:
  proxy:
    build: 
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - users
      - budget
    ports:
      - 80:80
    
  users:
    build:
      dockerfile: Dockerfile
      context: ./users
    ports:
      - '3001:3001'
    env_file: ./users/.env
    volumes:
      - ./users:/app/users

  budget:
    build:
      dockerfile: Dockerfile
      context: ./budget
    ports:
      - '3002:3002'
    env_file: ./budget/.env
    volumes:
      - ./budget:/app/budget